#! /usr/bin/env node

console.log(
    'This script populates some test books, authors, genres and bookinstances to your database. Specified database as argument - e.g.: node populatedb "mongodb+srv://cooluser:coolpassword@cluster0.lz91hw2.mongodb.net/local_library?retryWrites=true&w=majority"'
  );
  
  // Get arguments passed on command line
  const userArgs = process.argv.slice(2);
  

  //import Item from "./models/item";
  const Item = require("./models/item")
  const items = [];
  const animals = [];
  const animalinstances = [];
  const mongoose = require("mongoose");
  mongoose.set("strictQuery", false); // Prepare for Mongoose 7
  
  const mongoDB = userArgs[0];
  
  main().catch((err) => console.log(err));
  
  async function main() {
    console.log("Debug: About to connect");
    await mongoose.connect(mongoDB);
    console.log("Debug: Should be connected?");
  
    //await createAnimals();
    //await createAnimalInstances();
    await createItems();
    console.log("Debug: Closing mongoose");
    mongoose.connection.close();
  }
  
  async function itemCreate(name, category, sub_category, quantity, price, description, supplier, tags, lotSize, lastOrdered) {
    itemdetail = {
      name: name,
      category: category,
      sub_category: sub_category,
      quantity: quantity,
      price: price,
      description: description,
      supplier: supplier,
      tags: tags,
      lotSize: lotSize,
      lastOrdered: lastOrdered,
    };

    const item = new Item(itemdetail);
    await item.save();
    console.log(`added ${item.name}`)
  }


  // async function animalCreate(name, scientificname, current_version, description, diet, synth_date) {
  //   animaldetail = {
  //     name: name,
  //     scientificname: scientificname,
  //     current_version: current_version,
  //     description: description,
  //     diet: diet,
  //     synth_date: synth_date,
  //   };
  
  //   const animal = new Animal(animaldetail);
  //   await animal.save();
  //   animals.push(animal);
  //   console.log(`Added animal`);
  // }
  
  // async function animalInstanceCreate(animal, imprint, version, current_height, current_weight, birth_date, death_date) {
  //   animalinstancedetail = {
  //       animal: animal,
  //     imprint: imprint,
  //     version: version,
  //     current_height: current_height,
  //     current_weight: current_weight,
  //     birth_date: birth_date,
  //   };
  //   if (death_date != false) animalinstancedetail.death_date = death_date;
  
  //   const animalinstance = new AnimalInstance(animalinstancedetail);
  //   await animalinstance.save();
  //   animalinstances.push(animalinstance);
  //   console.log(`Added animalinstance: ${imprint}`);
  // }

  async function createItems2() {
    console.log('adding items....')
    await Promise.all([
      itemCreate(
      "Stock - Pigs", 
      "Feed", 
      "Livestock", 
      60, 
      129.99, 
      "Live Hogs", 
      "Ferdnandino Farms", 
      ["feeding", "livestock", "animals"],
      10, 
      "1990-08-23"),
      itemCreate(
        "Masticated Plant Matter",
        "Feed",
        "Plants",
        82,
        69.99,
        "50lb drum, crushed plant matter",
        "Brazil Milling Unico.",
        ['food', 'plants', 'feed', 'plant-matter'],
        10,
        "1991-11-11"
      ),
      ])}
  

  
 async function createItems() {
  console.log('adding items....')
  await Promise.all([
    itemCreate(
    "Luxury Bathrobe", 
    "Lodge_Amenities", 
    "Room_Supplies", 
    50, 
    29.99, 
    "Plush bath robes", 
    "Hotel Supplies Inc.", 
    ["bathroom", "hotel", "supplies"],
    50, 
    "1989-08-23"),
    itemCreate(
    "Safari Binoculars", 
    "Park_Equipment", 
    "Tools", 
    20, 
    29.99, 
    "Standard magnification, comfort grip, custom printed.", 
    "Wilderness Gear Co.", 
    ["binoculars", 
    "safari", 
    "wildlife"], 
    6, 
    "1989-11-05"),
    itemCreate("Premium Coffee Machine", 
    "Lodge_Amenities", 
    "Kitchen", 
    10, 
    199.99, 
    "Industrial Use Coffee/Expresso maker", 
    "BrewTech Solutions", 
    ["coffee machine", "Lodge_Amenities", "kitchen appliances", "food"],
    2, 
    "1989-02-17"),
    itemCreate("Souvenir T-Shirt", 
    "Park_Merchandise", 
    "Apparel", 
    200, 
    19.99, 
    "Package of S-XXL, 100% Cotton, Dinosaur Logo", 
    "Wild World Merchandise", 
    ["souvenir", "t-shirt", "gift shop",],
    20, 
    "1987-12-10"),
    itemCreate("Utility Bucket", 
    "Park_Equiptment", 
    "Feeding", 
    50, 
    9.99, 
    "Steel construction, 2 Gallon volume with handle", 
    "Zoo Supply Co.", 
    ["feeding bucket", "equiptment", "animal care",],
    10, 
    "1989-06-28"),
    itemCreate("Silk Pillowcase Set", 
    "Lodge_Amenities", 
    "Room_Supplies", 
    25, 
    39.99, 
    "Queen size, 100% Silk, multi-color pack", 
    "Dreamy Beddings", 
    ["pillowcase", "bedding", "supplies", "lodge"],
    5, 
    "1987-09-14"),
    itemCreate("Keychain", 
    "Park_Merchandise", 
    "Accessories", 
    200, 
    4.99, 
    "steel stamped, standard size. Custom logo fill", 
    "Wildlife Treasures", 
    ["keychain", "souvenir", "gift shop",],
    50, 
    "1988-08-01"),
    itemCreate("Luggage Rack", 
    "Lodge_Amenities", 
    "Room_Supplies", 
    40, 
    34.99, 
    "wood and steel construction, variable sizing", 
    "Travel Essentials Ltd.", 
    ["luggage rack", "hotel room accessories", "organization",], 
    10, 
    "1989-01-23"),
    itemCreate("Zoo Animal Plush Toy", 
    "Park_Merchandise", 
    "Toys", 
    150, 
    12.99, 
    "multicolored, dinosaur shaped plush toys, various sizes", 
    "Playful Pals Toys", 
    ["plush toy", "souvenir", "gift shop",],
    30, 
    "1987-11-18"),
    itemCreate("Mini Refrigerator", 
    "Lodge_Amenities", 
    "Room_Supplies",
    15, 
    129.99, 
    "12V power, 2 gallon volume, black", 
    "ChillMaster Appliances", 
    ["refrigerator", "hotel room", "appliances",], 
    3, 
    "1988-05-07"),
    itemCreate("Pith Hat", 
    "Park_Merchandise", 
    "Apparel" ,
    50, 
    14.99, 
    "Cloth constuction, various sizes. Custom logo", 
    "Zoo Gear Emporium", 
    ["hat", "souvenir", "gift shop",],
    10, 
    "1989-03-12"),
    itemCreate("Lab Coat",
    "Lab_Equipment",
    "Supplies",
    60,
    49.99,
    "White, heavy cotton. sizes XS-XXL",
    "LabWear Inc.",
    ["lab coat",
    "safety gear",
    "lab apparel",],
    5,
    "1988-09-05"),
    itemCreate("PCR Machine",
    "Lab_Equipment",
    "PCR",
    8,
    4999.99,
    "PCR machine, .002 Deg Tolerances, fits 10 0.2mL Tubes",
    "BioLab Innovations",
    ["PCR machine",
    "molecular biology equipment",
    "DNA amplification",],
    1,
    "1989-07-23"),
    itemCreate("Microcentrifuge",
    "Lab_Equipment",
    "Centrifugation",
    15,
    999.99,
    "Quickly separate samples with our compact and efficient microcentrifuge",
    "CentriTech",
   [ "microcentrifuge",
    "lab centrifuges",
    "sample preparation",],
    3,
    "1987-11-30"),
    itemCreate("Lab Gloves",
    "Lab_Equipment",
    "Supplies",
    200,
    9.99,
    "disposable lab gloves, sizes XXS-XXL",
    "SafetyGloves Inc.",
    ["lab gloves",
    "lab safety gear", "PPE",],
    50,
    "1988-04-18"
    ),
    itemCreate("Gel Electrophoresis System",
    "Lab_Equipment",
    "Electrophoresis",
    3,
    1999.99,
    "Precise 50V powersupply",
    "ElectraBio",
    ["gel electrophoresis system",
    "molecular biology equipment",
    "DNA analysis",],
    1,
    "1989-06-06"),
    itemCreate("Pipette Set",
    "Lab_Equipment",
    "Supplies",
    10,
    199.99,
    ".5mL, 1mL, .2mL sets",
    "PipetTech",
    ["pipette set",
    "lab supplies",
    "liquid handling",],
    5,
    "1987-12-20"),
    itemCreate("Incubator",
    "Lab_Equipment",
    "Incubation",
    25,
    2999.99,
    "Create optimal growth conditions for cells with our precise and temperature-controlled incubator",
    "CellGrow Systems",
    ["incubator",
    "lab incubation equipment",
    "cell culture",],
    5,
    "1988-08-15"),
    itemCreate("Lab Safety Goggles",
    "Lab_Equipment",
    "Supplies",
    60,
    14.99,
    "Comfortable and impact-resistant, plastic strap on lab safety goggles",
    "EyeSafe Inc.",
    ["lab safety goggles",
    "lab safety gear",
    "PPE",],
    10,
    "1989-02-03"),
    itemCreate("Autoclave",
    "Lab_Equipment",
    "Sterilization",
    10,
    4999.99,
    "Achieve complete sterilization with our reliable and efficient autoclave",
    ["SteriLab Solutions",
    "autoclave",
    "lab sterilization equipment",
    "equipment sterilization",],
    2,
    "1987-09-25"),
    itemCreate("Hydraulic Floor Jack",
    "Tools",
    "Garage",
    4,
    299.99,
    "2Ton rated lift, 2ft",
    "AutoPro Tools",
    ["floor jack",
    "garage tools",
    "lifting equipment",],
    1,
    "1989-07-15"),
    itemCreate("Off-Road Tires",
    "Vehicle_Parts",
    "Tires",
    30,
    249.99,
    "Conquer any terrain with our durable and high-performance off-road tires",
    "Rugged Wheels",
    ["off-road tires",
    "vehicle parts",
    "tires",],
    10,
    "1990-11-28"),
    itemCreate("Winch Kit",
    "Vehicle_Parts",
    "Accessories",
    20,
    699.99,
    "Get unstuck from any challenging situation with our versatile and powerful winch kit",
    "Trail Blazer Gear",
    ["winch kit",
    "off-road accessories",
    "recovery equipment",],
    2,
    "1989-05-02"),
    itemCreate("LED Light Bar",
    "Vehicle_Parts",
    "Lighting",
    15,
    149.99,
    "Illuminate the darkest trails with our bright and energy-efficient LED light bar",
    "Night Rider Solutions",
   ["LED light bar",
    "vehicle lighting",
    "lighting equipment",],
    5,
    "1991-03-18"),
    itemCreate("Heavy-Duty Toolbox",
    "Tools",
    "Storage",
    30,
    399.99,
    "Organize and protect your tools with our rugged and spacious heavy-duty toolbox",
    "GearMaster Storage",
   ["toolbox",
    "garage storage",
    "tool storage",],
    2,
    "1990-09-07"),
    itemCreate("Skid Plates",
    "Vehicle_Parts",
    "Accessories",
    25,
    199.99,
    "Shield your off-road vehicles' vulnerable components with our durable and reliable skid plates",
    "ArmorTech",
   ["skid plates",
    "vehicle protection",
    "underbody armor",],
    5,
    "1989-12-13"),
    itemCreate("Air Compressor",
    "Tools",
    "Garage",
    12,
    199.99,
    "Easily inflate tires and power pneumatic tools with our efficient and portable air compressor",
    "AirPro Solutions",
    ["air compressor",
    "garage equipment",
    "inflation tools",],
    2,
    "1991-06-02"),
    itemCreate("Keyboard",
    "IT_Equiptment",
    "Input Devices",
    15,
    99.99,
    "Standard keyboards for typing and inputting commands to the computer system",
    "TypeTech",
    ["keyboard",
    "computer peripherals",
    "input devices",],
    8,
    "1991-06-06"),
    itemCreate("Uninterruptible Power Supply (UPS)",
    "IT_Equiptment",
    "Power",
    2,
    1499.99,
    "UPS systems for providing backup power during outages and protecting equipment",
    "PowerGuard",
    ["uninterruptible power supply",
    "power management",
    "UPS",],
    1,
    "1987-12-30"),
    itemCreate("Backup Tape Drive",
    "IT_Equiptment",
    "Data_storage",
    4,
    599.99,
    "Tape drives for reliable backup and storage of large volumes of data",
    "DataSafe",
    ["backup tape drive",
    "data storage",
    "tape drive",],
    1,
    "1990-08-12"),
    itemCreate("Rack Cabinet",
    "IT_Equiptment",
    "Furniture",
    3,
    799.99,
    "Sturdy rack cabinets for housing and organizing computer equipment",
    "RackTech",
    ["rack cabinet",
    "data center equipment",
    "racks",],
    1,
    "1989-04-09"),
    itemCreate("Modem",
    "IT_Equiptment",
    "Networking",
    5,
    199.99,
    "Modems for connecting to remote systems and accessing external networks",
    "NetLink Communications",
    ["modem",
    "networking equipment",
    "modem",],
    2,
    "1988-06-27"),
    itemCreate("Dot Matrix Printer",
    "Printers",
    "Dot Matrix",
    15,
    399.99,
    "High-speed dot matrix printers for producing printed documents",
    "PrintMaster",
    ["dot matrix printer",
    "printers",
    "dot matrix",],
    3,
    "1991-01-18"),
    itemCreate("CRT Monitor",
    "IT_Equiptments",
    "Displays",
    26,
    499.99,
    "High-resolution CRT monitors for displaying computer data and visuals",
    "VisualTech",
    ["CRT monitor",
    "computer displays",
    "CRT",],
    5,
    "1988-09-14"),
    itemCreate("Wildlife Net",
    "Control_Equipment",
    "Nets",
    20,
    99.99,
    "Durable wildlife net for safely capturing and restraining animals",
    "CapturePro",
    ["wildlife net",
    "animal capture equipment",
    "nets",],
    5,
    "1992-09-08"),
    itemCreate("Infrared Motion Sensor",
    "Control_Equipment",
    "Motion Sensors",
    220,
    49.99,
    "Advanced infrared motion sensor for detecting animal movement in restricted areas",
    "GuardTech",
    ["infrared motion sensor",
    "security systems",
    "motion sensors",],
    30,
    "1991-11-21"),
    itemCreate("CCTV Camera",
    "Control_Equipment",
    "Cameras",
    35,
    199.99,
    "High-resolution CCTV camera for monitoring animal exhibits and restricted areas",
    "WatchfulEye",
    ["CCTV camera",
    "surveillance equipment",
    "security cameras",],
    5,
    "1990-01-02"),
    itemCreate("Handling Gloves",
    "Control_Equipment",
    "Apparel",
    40,
    29.99,
    "Heavy-duty animal handling gloves for protecting against bites and scratches",
    "SafeHands",
    ["animal handling gloves",
    "protective gear",
    "gloves",],
    10,
    "1991-05-15"),
    itemCreate("Animal Tracking Collar",
    "Control_Equipment",
    "Tracking Devices",
    20,
    399.99,
    "GPS-enabled tracking collar for monitoring the location and movement of animals",
    "TrackMaster",
    ["animal tracking collar",
    "animal monitoring",
    "tracking devices",],
    2,
    "1992-06-28"),
    itemCreate("Emergency Alarm System",
    "Control_Equipment",
    "Alarms",
    8,
    999.99,
    "Robust emergency alarm system for rapid response and evacuation during animal-related emergencies",
    "ZooAlert",
   [ "emergency alarm system",
    "safety systems",
    "alarms",],
    1,
    "1993-03-10"),
    itemCreate("Surgical Scissors",
    "Medical_Supplies",
    "Instruments",
    10,
    49.99,
    "Precision surgical scissors for performing delicate veterinary procedures",
    "VetPro Instruments",
    ["surgical scissors",
    "surgical instruments",
    "scissors",],
    2,
    "1991-02-18"),
    itemCreate("Veterinary Stethoscope",
    "Medical_Supplies",
    "Instruments",
    10,
    79.99,
    "High-quality stethoscope for auscultation and diagnosing animals' health conditions",
    "AnimalCare",
    ["veterinary stethoscope",
    "diagnostic equipment",
    "stethoscopes",],
    5,
    "1991-09-03"),
    itemCreate("Sterile Gloves",
    "Medical_Supplies",
    "Apparel",
    100,
    19.99,
    "Disposable sterile gloves for maintaining hygienic conditions during veterinary procedures",
    "SteriHands",
    ["sterile gloves",
    "medical supplies",
    "gloves",],
    50,
    "1990-11-27"),
    itemCreate("Digital Thermometer",
    "Medical_Supplies",
    "Instruments",
    15,
    39.99,
    "Accurate digital thermometer for measuring animals' body temperature",
    "TempCheck",
    ["digital thermometer",
    "diagnostic equipment",
    "thermometers",],
    3,
    "1992-07-15"),
    itemCreate("Syringe and Needle Set",
    "Medical_Supplies",
    "Instruments",
    50,
    9.99,
    "Disposable syringe and needle set for administering medications and vaccinations",
    "CareMed",
   [ "syringe and needle set",
    "medical equipment",
    "syringes and needles",],
    25,
    "1991-04-22"),
    itemCreate("Veterinary Suture Kit",
    "Medical_Supplies",
    "Disposables",
    3,
    149.99,
    "Comprehensive veterinary suture kit for closing wounds and surgical incisions",
    "SutureCare",
    ["veterinary suture kit",
    "surgical supplies",
    "suture kits",],
    1,
    "1993-01-09"),
    itemCreate("Dental Scaling Tools",
    "Medical_Supplies",
    "Instruments",
    5,
    89.99,
    "Specialized dental scaling tools for maintaining oral health in animals",
    "DentaVet",
    ["dental scaling tools",
    "dental instruments",
    "scaling tools",],
    2,
    "1990-06-12"),
    itemCreate("X-Ray Machine",
    "Medical_Supplies",
    "Diagnostics",
    2,
    4999.99,
    "Advanced veterinary X-ray machine for capturing detailed radiographic images",
    "RadiantVet",
   [ "X-ray machine",
    "diagnostic equipment",
    "X-ray machines",],
    1,
    "1992-05-05"),
    itemCreate("Wound Dressing",
    "Medical_Supplies",
    "Disposables",
    20,
    29.99,
    "Antimicrobial wound dressing for promoting healing and preventing infections",
    "HealSafe",
    ["wound dressing",
    "medical supplies",
    "wound care",],
    10,
    "1991-12-18"),
    itemCreate(
      "Animal Feed - Bulk",
      "Feed",
      "Grain",
      22,
      69.99,
      "50 lb sack of milled feed",
      "Lopez Milling Co.",
      ['food', 'grain', 'feed', 'plant-matter'],
      10,
      "1991-05-11"
    ),

  ])
 }


  
  // async function createAnimalInstances() {
  //   console.log("Adding authors");
  //   await Promise.all([
  //       animalInstanceCreate(
  //       animals[0],
  //       "TR05",
  //       "v2.0",
  //       "2.9",
  //       "8.2",
  //       "1990-12-05",
  //     ),
  //     animalInstanceCreate(
  //       animals[0],
  //       "TR06",
  //       "v2.0",
  //       "2.9",
  //       "8.6",
  //       "1990-12-06",
  //     ),
  //     animalInstanceCreate(
  //       animals[0],
  //       "TR11",
  //       "v2.1",
  //       "1.5",
  //       "5.4",
  //       "1990-12-29",
  //     ),
  //     animalInstanceCreate(
  //       animals[1],
  //       "ST08",
  //       "v1.3",
  //       "4.5",
  //       "2.4",
  //       "1990-01-13",
  //     ),
  //     animalInstanceCreate(
  //       animals[1],
  //       "ST16",
  //       "v1.6",
  //       "4.1",
  //       "2.2",
  //       "1990-08-21",
  //     ),
  //     animalInstanceCreate(
  //       animals[2],
  //       "BR09",
  //       "v1.9",
  //       "21.5",
  //       "20.2",
  //       "1989-11-07",
  //     ),
  //     animalInstanceCreate(
  //       animals[3],
  //       "TR03",
  //       "v2.1",
  //       "4.2",
  //       "11.1",
  //       "1991-02-07",
  //     ),
  //     animalInstanceCreate(
  //       animals[4],
  //       "VR13",
  //       "v4.5",
  //       "2.4",
  //       "180",
  //       "1991-02-07",
  //     ),
  //     animalInstanceCreate(
  //       animals[4],
  //       "VR21",
  //       "v4.2",
  //       "2.3",
  //       "171",
  //       "1990-12-27",
  //     ),
  //     animalInstanceCreate(
  //       animals[4],
  //       "VR10",
  //       "v4.3",
  //       "2.0",
  //       "160",
  //       "1990-12-30",
  //     ),
  //     animalInstanceCreate(
  //       animals[5],
  //       "DL02",
  //       "v1.4",
  //       "2.2",
  //       "0.5",
  //       "1991-06-09",
  //     ),
  //     animalInstanceCreate(
  //       animals[6],
  //       "PC21",
  //       "v3.4",
  //       "0.8",
  //       "30",
  //       "1990-06-16",
  //     ),
  //     animalInstanceCreate(
  //       animals[6],
  //       "PC25",
  //       "v3.8",
  //       "0.7",
  //       "28",
  //       "1990-11-09",
  //     ),
  //     animalInstanceCreate(
  //       animals[6],
  //       "PC28",
  //       "v3.8",
  //       "0.6",
  //       "27",
  //       "1990-11-09",
  //     ),
  //     animalInstanceCreate(
  //       animals[6],
  //       "PC15",
  //       "v3.0",
  //       "0.7",
  //       "29",
  //       "1990-04-30",
  //     ),
  //   ]);
  // }